version: '3'
services:
  hmaster:
    image: genieouz/hadoop-setup:1.0
    networks:
      - default
    tty: true
    stdin_open: true
    ports:
      - "50070:50070"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    hostname: hadoop-master
    container_name: hadoop-master
    restart: always
  hslave1:
    image: genieouz/hadoop-setup:1.0
    networks:
        - default
    tty: true
    stdin_open: true
    ports:
      - "8040:8042"
    hostname: hadoop-slave1
    container_name: hadoop-slave1
    restart: always
  hslave2:
    image: genieouz/hadoop-setup:1.0
    networks:
        - default
    tty: true
    stdin_open: true
    ports:
      - "8041:8042"
    hostname: hadoop-slave2
    container_name: hadoop-slave2
    restart: always

networks:
  default:
    driver: bridge
    